name: myclipboard
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # win32: ^5.4.0
  # win32: ^5.5.0
  shared_preferences: ^2.1.0
  cupertino_icons: ^1.0.6
  path_provider: ^2.0.11  # 新增加的依赖
  # clipboard_watcher: ^0.2.1
  file_picker: ^5.0.0
  # clipboard_listener: ^2.0.0
  # clipboard_watcher: ^0.2.0
  # clipboard_watcher: ^0.2.1
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png


flutter_icons:
  android: true
  ios: true
  # windows: true
  image_path: "assets/icon/app_icon.png" 
  # flutter pub run flutter_launcher_icons:main
